# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

target 'enjoy' do
    pod 'MFSideMenu', '~> 0.5.4'
    pod 'AFNetworking', '~> 2.0'
end

target 'enjoyTests' do

end